# Generated by Django 6.0 on 2025-12-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Endpoint name', max_length=255)),
                ('app_name', models.CharField(help_text='Django app name', max_length=100)),
                ('protocol', models.CharField(choices=[('REST', 'REST API'), ('SOAP', 'SOAP API')], max_length=10)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('SOAP', 'SOAP Operation')], max_length=10)),
                ('path', models.CharField(help_text='API path', max_length=500)),
                ('description', models.TextField()),
                ('request_example', models.TextField(blank=True, help_text='Example request body')),
                ('response_example', models.TextField(blank=True, help_text='Example response')),
                ('parameters', models.TextField(blank=True, help_text='Query parameters or path parameters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_name', 'protocol', 'path'],
            },
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number (e.g., 1.0.0)', max_length=50)),
                ('change_type', models.CharField(choices=[('feature', 'New Feature'), ('enhancement', 'Enhancement'), ('bugfix', 'Bug Fix'), ('breaking', 'Breaking Change'), ('documentation', 'Documentation')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('app_affected', models.CharField(blank=True, help_text='App affected by this change', max_length=100)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('command', models.TextField(blank=True, help_text='Command to execute')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
